{% set version = '2.1.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pracma
  version: {{ version|replace("-", "_") }}

source:
  fn: pracma_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/pracma_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pracma/pracma_{{ version }}.tar.gz
  sha256: c95993af91dba98307b3b8660cda8f87d8bbd2ecc2ebe5deabeba9fd043b9ba1

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('pracma')"           # [not win]
    - "\"%R%\" -e \"library('pracma')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=pracma
  license: GPL (>= 3)
  summary: ' Provides a large number of functions from numerical analysis and linear algebra,
    numerical optimization, differential equations, time series, plus some well-known
    special mathematical functions. Uses ''MATLAB'' function names where appropriate
    to simplify porting.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
