travis:
  secure:
    BINSTAR_TOKEN: FN+ODNL9XNfHQfX5YaPYx2DDrqN2ngAXeJVh4WPPba70CjqtfpnS3Zgtg89oH+0TtRUUg7c6Zc/4bBQxDPpMzxR7CQbYiROZrxg/wgXB8Pm4j0kzRR5dnhzirr7SWyXeD07C4DMITPAdUVRL9nuUusxqNYc2+V87rV6pQRWRi+EWgbChkRV++NyUz6Lj92xytsedhlWvzpDzaZuIslkoVjmBr6Q2CvYxPn1IC8kF5Uw/BQyglsbPaN83XZS8n26X/LtNlkYlKyCrQvMHl0RW7p7cX7Z6qVWQpeH9qKgHwwhRm7GC8UB3KtrjVzpuwcA1J72orGBjjzIh27lKAZDlCvqzrPtjJMiKv1uulj7i6ISCrCi3gL5/EbFy0mCXWOUfnV7fXgp7KCWXTpgomvACVX7X3/HMoO+158ePPwQ3VO9ChuaIoKS6z5mHP/vj1rFP1Hi7svXfGRAfECOlOuDeCy9lJrJDGH45ntlCOHcitB/m/h2dLfKb1eoQ+Un4+av2paI/kISDlNCEJvfTFK5e1169UwXdaWpEvj9XaLLLAju7J1LEo0ochWI94Ui2S8bSn4n6rg8byUP78kSSzV9Ar8kKvPvYOTb/FxeS14YBCu+7/HksfQmAY6tPO9YvjlpV6STe1fweX0omHcWfYV3O03WVzMZQxAoZvAs33k7gxGg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
