travis:
  secure:
    BINSTAR_TOKEN: lCMx5Hn5cZxZPXPid1E8t1Hf0mbFU3Xx8Z8/5e4s6jHL/QDlHxo+sPn3yf+zyC/dXpZZOqaIRa6F3Wi/nsiNyEw8IDFpDDCpPAYNHmW9uUN31DSL1NbSFW0/WAd8FBW1CHBo0BbpuAHu8HtnWD5eq+nZGA0F0hZb2I67ZJu6G0CaPjzie6LAYl7u8Vtx9ROsfZN745rXbu+Slos9lMLu/5/vIIWGqdWslZ7iUSLY0JZR/YGHcai5OA0SQumyTwfbfFj5u9cAXh4XTQus9BFv6llOM+cUVI0GgWb2dM78kEixFPFN4FKibkFGlyex6BylQo3MSOi42k31HFVvxmfGky0E6nlUn2ZDJ9V+G2Ya0IX/uyCWMDRxhRlnf9uDOOY40QYyYTNyzNPdUHUpm3FIJq47cVsRo7TYg8psUpB87z4jW4NoWvRmwJNerSW/bQShRmaT87gx+WmkwnrgPUOEPnsAYPHY7piWW3CJT/n0tWFUEefgdOTm+20hfwuxg9wcNsKsZdqnfCz5hKUSoatJO2/IZQ7jRN+YQ2HuSjSVPuS0kaT5/xG5337+c6Q0qFdkVf5W0HiTBGSsEcUhzFUYKuFX8eWH7KUSd0So5GUWSG//NyiXdygI0IGu8MNhGhGT0qqRl849ECmAGmxmSvbZYZ5I1glMaAPmyrr5sxuNw1E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
